const { LAB_ADMIN_DEFAULT_PERMISSIONS} = [
  "TENANT.PROFILE.VIEW",
  "TENANT.PROFILE.UPDATE",

  "TENANT.PATIENTS.CREATE",
  "TENANT.PATIENTS.VIEW",
  "TENANT.PATIENTS.UPDATE",

  "TENANT.VISITS.CREATE",
  "TENANT.VISITS.VIEW",
  "TENANT.VISITS.UPDATE",

  "TENANT.BILLING.CREATE",
  "TENANT.BILLING.VIEW",
  "TENANT.BILLING.UPDATE",

  "TENANT.RATELISTS.MANAGE",

  "TENANT.SAMPLES.CREATE",
  "TENANT.SAMPLES.VIEW",
  "TENANT.SAMPLES.UPDATE",

  "TENANT.RESULTS.ENTER",
  "TENANT.RESULTS.VIEW",

  "TENANT.REPORTS.VIEW",
  "TENANT.REPORTS.EXPORT",

  "TENANT.STAFF.MANAGE"
];

module.exports = { LAB_ADMIN_DEFAULT_PERMISSIONS };